# Generated by Django 6.0.4 on 2026-04-18 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('ussd_string', models.CharField(max_length=100)),
                ('tel_uri', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('dialed', 'Dialed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_sessions', to='locations.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
