# Generated by Django 6.0.4 on 2026-04-22 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('ussd_string', models.CharField(max_length=100)),
                ('tel_uri', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('dialed', 'Dialed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='locations.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_sessions', to='vendors.vendor')),
            ],
            options={
                'db_table': 'payments_parking_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSavedLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('last_visited_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='locations.parkinglot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_lots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_user_saved_lot',
                'ordering': ['-visit_count', '-last_visited_at'],
                'unique_together': {('user', 'lot')},
            },
        ),
    ]
