# Generated by Django 6.0.4 on 2026-04-22 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('ussd_shortcode', models.CharField(max_length=20)),
                ('ussd_chain_template', models.CharField(help_text='USSD string template e.g. *483*1*{plate}*{phone}#', max_length=100)),
                ('adapter_class', models.CharField(help_text='Dotted Python path to the adapter class e.g. vendors.adapters.kaps.KAPSAdapter', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('sandbox_mode', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vendors_vendor',
            },
        ),
    ]
